In [14]:
import pandas as pd
import numpy as np
import math

In [3]:
#读入鸢尾花数据集
ds = pd.read_table("irisdataset.txt", sep = ",", header = None)
ds.head()

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [4]:
"""
数据说明：属性一是萼片长度，属性二是萼片宽度，属性三是花瓣长度，属性四是花瓣宽度
类有：Setosa,Versicolour,Virginica
显然讨论的属性数据都是连续数据
"""

"""
现在调整策略,直接用创建好的数据集进行实践.
"""

'\n现在调整策略,直接用创建好的数据集进行实践.\n'

In [15]:
dataset = np.array([(0,2,0,0,0), (0,2,0,1,0), (1,2,0,0,1), (2,1,0,0,1), 
                   (2,0,1,0,1), (2,0,1,1,0), (1,0,1,1,1), (0,1,0,0,0), 
                   (0,0,1,0,1), (2,1,1,0,1), (0,1,1,1,1), (1,1,0,1,1), 
                   (1,2,1,0,1), (2,1,0,1,0)])
dataset = np.asmatrix(dataset)

In [8]:
m,n = dataset.shape
s = dataset[:,n-1]
s1 = s.getA()
s2 = np.unique(s1)
s3 = len(s2)
s4 = np.zeros((s3,2))
s4 = np.asmatrix(s4)
s2 = np.asmatrix(s2)
s2 = s2.T
#s4[0,1]
#s2[0,:]
#s4[0,1] = s2[0,:]
#s4
#s[1]
#s2[1]

In [9]:
for i in range(0, s3):
        s4[i,0] = s2[i,:]
        for j in range(0, m):
            if (s[j,:] == s2[i,:]):
                s4[i,1] = s4[i,1]+1
s4

matrix([[0., 5.],
        [1., 9.]])

In [10]:
s4[:,1] = s4[:,1]/m
s4

matrix([[0.        , 0.35714286],
        [1.        , 0.64285714]])

In [87]:
s4[0,0]

0.0

In [11]:
entropy = 0;  
for i in range(0, s3):
    entropy = entropy - s4[i,1] * math.log(s4[i,1], 2);#似乎有问题
entropy

0.9402859586706309

In [23]:
#编写计算熵值的函数
def calEntropy(dataset):
    [m,n] = dataset.shape#提取数据的维度信息
    
    label = dataset[:,(n-1)]#类别列向量
    label_del = np.unique(label.getA())#提取类别信息
    
    numLabel = len(label_del)#类别的数目
    
    label_del = np.asmatrix(label_del)
    label_del = label_del.T#对齐数据格式
    
    prob = np.zeros((numLabel, 2))#创建数组行数numLabel，列数为2
    
    prob = np.asmatrix(prob)#转为矩阵
    
    
    #统计各类数量并且记录在一个矩阵中,其实可以直接调用numpy的stats函数,可改的
    for i in range(0, numLabel):
        prob[i,0] = label_del[i,:]
        for j in range(0, m):
            if label[j,:] == label_del[i,:]:
                prob[i,1] = prob[i,1]+1
    
    
    #计算熵
    prob[:,1] = prob[:,1] / m  
    entropy = 0
    for i in range(0, numLabel):
            entropy = entropy - prob[i,1] * math.log(prob[i,1], 2)
    return entropy

In [21]:
"""
错误调试方法
[m,n] = dataset.shape#提取数据的维度信息
    
label = dataset[:,(n-1)]#类别列向量
label_del = np.unique(label.getA())#提取类别信息
    
numLabel = len(label_del)#类别的数目
    
label_del = np.asmatrix(label_del)
label_del = label_del.T#对齐数据格式
    
prob = np.zeros((numLabel, 2))#创建数组行数numLabel，列数为2
    
prob = np.asmatrix(prob)#转为矩阵
    
    
    #统计各类数量并且记录在一个矩阵中,其实可以直接调用numpy的stats函数,可改的
for i in range(0, numLabel):
    prob[i,0] = label_del[i,:]
    for j in range(0, m):
        if label[j,:] == label_del[i,:]:
            prob[i,1] = prob[i,1]+1
    
    
    #计算熵
#prob[:,1] = prob[:,1] / m  
#entropy = 0
#for i in range(0, numLabel):
#        entropy = entropy - prob[i,1] * math.log(prob[i,1], 2)
#return entropy
"""

In [62]:
[m,n] = dataset.shape
subSet = dataset.getA()
set_l = np.unique(subSet)
a = len(set_l)
for i in range(0,a):
    for j in range(0,n-1):
        condition = subSet[:,j] == a
        np.extract(condition, subSet[:,4])

array([0, 0, 0, 1, 1])

In [57]:
dataset

matrix([[0, 2, 0, 0, 0],
        [0, 2, 0, 1, 0],
        [1, 2, 0, 0, 1],
        [2, 1, 0, 0, 1],
        [2, 0, 1, 0, 1],
        [2, 0, 1, 1, 0],
        [1, 0, 1, 1, 1],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 1],
        [2, 1, 1, 0, 1],
        [0, 1, 1, 1, 1],
        [1, 1, 0, 1, 1],
        [1, 2, 1, 0, 1],
        [2, 1, 0, 1, 0]])

In [ ]:
#划分数据,无法解决很多问题,根据value可以划出多个子集，目前就是这个函数无法解决。
def splitData(data, axis, value):
    [m,n]=dataset.shape
    subSet = 
    return subSet

In [32]:
[a,b] = dataset.shape
s1 = b-1
s2 = calEntropy(dataset)

s3 = 0
s4 = 0

k = (dataset[:,0]).getA()#第1列提取出来
feaTemp = np.unique(k)#第1列的不重复值。特征属性值
numf = len(feaTemp)
newentropy = 0
for i in range(0,numf):
    subset = splitdata()

array([0, 1, 2])

In [1]:
#选择信息增益最大
def chBestFea(dataset):
    [m,n] = dataset.shape
    
    numOfFea = n-1
    baseEntropy = calEntropy(dataset)
    
    bestInfoGain = 0
    bestFea = 0
    
    for j in range(0,numOfFea):
        k = (dataset[:,j]).getA()
        feaTemp = np.unique(k)#提取第j列有多少个属性,
        numF = len(feaTemp)#属性的个数
        newEntropy = 0
        for i in range(0,numF):
            subSet = splitData(dataset,j,feaTemp[i,:])#研究清楚这个函数
            [a, b] = subSet.sahpe
            prob = a/m
            newEntropy = newEntropy + prob * calEntropy(subSet)#从前文角度看，subSet是matrix
            
        infoGain = baseEntropy - newEntropy
        
        if infoGain > bestInfoGain:
            bestInfoGain = infoGain
            bestFeature = j

SyntaxError: invalid syntax (<ipython-input-1-78fda1dbdb74>, line 24)

In [ ]:
 %% 选择信息增益最大的特征  
    function [ bestFeature ] = chooseBestFeature( data )  
        [m,n] = size(data);% 得到数据集的行列信息，m记录行数，n记录列数 
          
        % 统计特征的个数  
        numOfFeatures = n-1;%最后一列是类别  
        % 原始的熵，调用函数见下面的定义  
        baseEntropy = calEntropy(data);  
          
        bestInfoGain = 0;%初始化信息增益  
        bestFeature = 0;% 初始化最佳的特征位  
          
        % 挑选最佳的特征位  
        for j = 1:numOfFeatures  
            featureTemp = unique(data(:,j));  %再次用到unique函数
            numF = length(featureTemp);%属性的个数  
            newEntropy = 0;%划分之后的熵  
            for i = 1:numF  
                subSet = splitData(data, j, featureTemp(i,:));  
                [m_1, n_1] = size(subSet);  
                prob = m_1./m;  
                newEntropy = newEntropy + prob * calEntropy(subSet);  
            end  
              
            %计算增益  
            infoGain = baseEntropy - newEntropy;  
              
            if infoGain > bestInfoGain  
                bestInfoGain = infoGain;  
                bestFeature = j;  
            end  
        end  
    end  