In [ ]:
"""
改进id3_learn.ipynb中的不足,在python的pandas和numpy中找寻相关的api简化一些函数。
"""

In [ ]:
"""
计算初始熵值的改进方法，pandas实现。耗时耗力。
"""

In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = np.array([(0,2,0,0,0), (0,2,0,1,0), (1,2,0,0,1), (2,1,0,0,1), 
                   (2,0,1,0,1), (2,0,1,1,0), (1,0,1,1,1), (0,1,0,0,0), 
                   (0,0,1,0,1), (2,1,1,0,1), (0,1,1,1,1), (1,1,0,1,1), 
                   (1,2,1,0,1), (2,1,0,1,0)])

In [13]:
#dataset[:,0]

array([0, 0, 1, 2, 2, 2, 1, 0, 0, 2, 0, 1, 1, 2])

In [12]:
#按列循环
k = []
for i in range(0,5):
    k.append(dataset[:,i])
k

[array([0, 0, 1, 2, 2, 2, 1, 0, 0, 2, 0, 1, 1, 2]),
 array([2, 2, 2, 1, 0, 0, 0, 1, 0, 1, 1, 1, 2, 1]),
 array([0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0]),
 array([0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1]),
 array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])]

In [16]:
value = 1
[m, n] = dataset.shape
retDataSet = []
for j in dataset[:,0]:
    if j == value:
        retDataSet.append(j)
retDataSet

[1, 1, 1, 1]

In [ ]:
#分离数据
def splitDataSet(dataSet, axis, value):
    retDataSet = []
    for featVec in dataSet:
        if featVec[axis] == value:
            reducedFeatVec = featVec[:axis]
            reducedFeatVec.extend(featVec[axis+1:])
            retDataSet.append(reducedFeatVec)
     
    return retDataSet

In [ ]:
function [ subSet ] = splitData( data, axis, value )  
        [m,n] = size(data);%得到待划分数据的大小  
          
        subSet = data;  
        subSet(:,axis) = [];  %%需要知道axis的参数数据，上文是j是列，[]是一个空列表
        k = 0;  
        for i = 1:m  
            if data(i,axis) ~= value  
                subSet(i-k,:) = [];  %%奇怪的代码
                k = k+1;  
            end  
        end     
    end  
